import os
import sys

def main():
    print("Hello World")

if __name__ == "__main__":
    main()

# I want to create a project where a source document (PDF) is used to evaluate the responses generated by a large language model (LLM). The process works like this: the LLM's response will be broken down into paragraphs, and each paragraph will be searched for in the PDF using a Chroma/vector database retriever. A separate LLM agent will then assess whether the generated response is accurate based on the content of the PDF.